---
- hosts: all
  remote_user: root

  vars_files:
    - "vars/vaulted-passwords.yml"

  tasks:

    - name: add deployer group
      group: name=deployer system=yes
    
    - name: add deployer user
      user: 
        name: deployer
        password: "{{ vaulted_deployer_password }}"
        comment: Deployer
        system: yes
        group: deployer
        groups: deployer
        state: present
        shell: /bin/bash
        
    - name: add public key of ssh key used to login as deployer from managing machine
      authorized_key:
        user: deployer
        key: "{{ lookup('file', '/Users/greg.kedge/.ssh/crisp_emeraldpool_root_rsa.pub') }}"

    - name: add tugboat public key of ssh key used to login as deployer from managing machine
      authorized_key:
        user: deployer
        key: "{{ lookup('file', '/Users/greg.kedge/.ssh/tugboot_root_rsa.pub') }}"

    - name: Do not require tty for sudo'ers
      lineinfile:
        dest: /etc/sudoers
        regexp: "requiretty"
        state: absent
        validate: "visudo -cf %s"
    
    - name: Add deployer group to sudoers file and validate
      lineinfile:
        dest: /etc/sudoers
        regexp: '^%deployer'
        line: '%deployer ALL=(ALL) NOPASSWD: ALL'
        state: present
        validate: "visudo -cf %s"
    
