---
- hosts: all
  remote_user: deployer
  become: yes 

  vars_files:
    - vars/main.yml
    - vars/vaulted-passwords.yml

  pre_tasks:
    - debug: msg="subDomain = {{ subDomain }}"
  
  roles:
    - { role: system, subDomain: react, zoneeditPassword: "{{vaulted_zoneedit_password}}" }
