- hosts: all
  remote_user: deployer
  become: yes

  tasks:
    - debug: msg="ansible_virtualization_type = {{ansible_virtualization_type}}"

    - name: Restart wildfly
      service: name=wildfly state=restarted
