---
- hosts: all
  remote_user: deployer
  become: yes
  
  vars_files:
    - vars/main.yml
    - [ "vars/{{ ansible_virtualization_type }}-passwords.yml", "vars/vaulted-passwords.yml" ]
    
  pre_tasks:
  - name: VM type?
    debug: msg="VM type vars = vars/{{ ansible_virtualization_type }}-passwords.yml"
  
  post_tasks:
  - name: Restart nginx.
    service: name=nginx state=restarted enabled=yes
