---
# roles/wildfly/install/module/postgresql-9.2-1004/handlers/main.yml 

- name: start wildfly 
  service: name=wildfly state=started

- name: stop wildfly 
  service: name=wildfly state=stopped

- name: restart wildfly 
  service: name=wildfly state=restarted
